version: 2.1

#orbs:
  #aqaptest: aqaptest/testsuite-runner@0.0.1
  
executors:
  machine-executor:
    machine:
      image: ubuntu-2004:202010-01
      
jobs:
  execute-suite-command:
    environment:
       CLOUDQA_API_KEY: "MPzTXks8vUKo0/at0yExuMZ0DqH+Nd+1/xybvc4pdiI="
       CLOUDQA_SUITE_ID: 2096
    executor: machine-executor
    steps:
      - run: sudo apt-get update && sudo apt-get install -y jq
      - run: curl -O https://cquserfiles.s3.amazonaws.com/6394/28cb57ae611041d2a44ae2bcb3bbad66/cloudqa-app-circleci.sh
      - run: bash cloudqa-app-circleci.sh
      
workflows:
  test:
    jobs:
      - execute-suite-command
