version: 2.1

#orbs:
  #aqaptest: aqaptest/testsuite-runner@0.0.1
  
executors:
  machine-executor:
    machine:
      image: ubuntu-2004:202010-01
      
jobs:
  execute-suite-command:
    parameters:
      api-key:
        type: string
        description: Your CloudQA API key.
      suite-id:
        type: string
        description: ID of the CloudQA suite to execute.
      browser:
        type: string
        description: (optional) Modify the browser to execute your suite against, defaults to `Chrome`.
        default: 'Chrome'
      build-tag:
        type: string
        description: (optional) Modify the build tag to set build id of your suite, defaults to ``.
        default: ''
      base-url:
        type: string
        description: (optional) Modify the base url to execute your suite against, defaults to ``.
        default: ''
      variables:
        type: string
        description: (optional) Modify the variables to set variables of your suite, defaults to ``.
        default: ''
      is-sequential-execution:
        type: boolean
        description: (optional) Modify the is sequential execution to execution type(sequential, parallel) of your suite, defaults to `true`.
        default: true
      environment-name:
        type: string
        description: (optional) Modify the environment name to execute your suite against, defaults to ``.
        default: ''
    executor: machine-executor
    steps:
      - run: sudo apt-get update && sudo apt-get install -y jq
      - run: curl -O https://cquserfiles.s3.amazonaws.com/6394/27674afb424643b8934cf89046ffad7e/cloudqa-app-circleci_v2.sh
      - run: bash cloudqa-app-circleci_v2.sh
      
workflows:
  test:
    jobs:
      - execute-suite-command:
          api-key: "MPzTXks8vUKo0/at0yExuMZ0DqH+Nd+1/xybvc4pdiI="
          suite-id: "2682"
