version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Run tests
          command: test
workflows:
  version: 2
  build:
    jobs:
      - build
