version: 2
jobs:
  build:
    environment:
       CLOUDQA_API_KEY: "MPzTXks8vUKo0/at0yExuMZ0DqH+Nd+1/xybvc4pdiI="
       CLOUDQA_SUITE_ID: 2682
       CLOUDQA_BROWSER: Firefox
       CLOUDQA_BUILD_TAG: "Variable test Circle CI"
       CLOUDQA_BASE_URL: "http://www.seleniumeasy.com/"
       CLOUDQA_VARIABLES: "cicd1=3,cicd2=3,cicd3=6"
       CLOUDQA_SEQUENTIAL_EXECUTION: FALSE
       CLOUDQA_ENVIRONMENT_NAME: "p"
    machine:
      image: ubuntu-2004:202010-01 # recommended linux image
    steps:
      - run: sudo apt-get update && sudo apt-get install -y jq
      - run: curl -O https://cquserfiles.s3.amazonaws.com/6394/28cb57ae611041d2a44ae2bcb3bbad66/cloudqa-app-circleci.sh
      - run: bash cloudqa-app-circleci.sh
