version: 2
jobs:
  build:
    environment:
       CLOUDQA_API_KEY: "MPzTXks8vUKo0/at0yExuMZ0DqH+Nd+1/xybvc4pdiI="
       CLOUDQA_SUITE_ID: 2004
       CLOUDQA_BROWSER: Chrome
       CLOUDQA_BUILD_TAG: "Parallel test Circle CI"
       CLOUDQA_BASE_URL: "http://the-internet.herokuapp.com/"
       CLOUDQA_VARIABLES: "var1=val1,var2=val2"
       CLOUDQA_SEQUENTIAL_EXECUTION: FALSE
    machine:
      image: ubuntu-2004:202010-01 # recommended linux image
    steps:
      - run: sudo apt-get update && sudo apt-get install -y jq
      - run: curl -O https://cquserfiles.s3.amazonaws.com/6394/28cb57ae611041d2a44ae2bcb3bbad66/cloudqa-app-circleci.sh
      - run: bash cloudqa-app-circleci.sh
